### ISSUE TITLE
Can't retrieve the model from amazon

### ISSUE THREAD

**Issue by jadecranberry** [allenai/scifact#8]
Hi Guys, 
Thanks for this amazing project!

I tried to 

!bash download-model.sh rationale roberta_large scifact

with google colab. But the access was forbidden. Error messages are

--2021-01-27 18:08:46--  https://scifact.s3-us-west-2.amazonaws.com/release/2020-12-17/models/rationale_roberta_large_scifact.tar.gz
Resolving scifact.s3-us-west-2.amazonaws.com (scifact.s3-us-west-2.amazonaws.com)... 52.218.180.1
Connecting to scifact.s3-us-west-2.amazonaws.com (scifact.s3-us-west-2.amazonaws.com)|52.218.180.1|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-01-27 18:08:46 ERROR 403: Forbidden.

tar (child): model/rationale_roberta_large_scifact.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
rm: cannot remove 'model/rationale_roberta_large_scifact.tar.gz': No such file or directory

The weird thing is I was able to download the model yesterday. Thanks in advance for your answers!

**Comment by dwadden** [comment]
Hi,

Thanks for your interest, and sorry for the confusion! If you pull the latest version of SciFact and re-run that command, things should work again.

Yesterday I moved the models to https://scifact.s3-us-west-2.amazonaws.com/release/latest/models/.

I did this so that I don't have to update the date in the URL (e.g. `2020-12-17`) every time we do a new release. I'll close this now; if pulling and re-running doesn't work, feel free to re-open.

Dave
